name: pam4lab
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/red_wine.png
    - assets/white_wine.png
    - assets/img_1.png
    - assets/img_2.png
    - assets/img_3.png
    - assets/img_4.png
    - assets/v3.json
  